# Generated by scripts/update-agent.py; update all artifacts together.
class LensoAgent < Formula
  desc "Coding agent with replaceable tools, models, and memory"
  homepage "https://github.com/LioRael/lenso-agent"
  license "MIT"

  depends_on "ripgrep"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :sequoia

    on_arm do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-v0.1.10-darwin-aarch64.tar.gz"
      sha256 "f9389a4d0978e53e22d88777e7bd87521bcf41e3b0ba9377944c10554f504167"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-cli-v0.1.10-darwin-aarch64.tar.gz"
        sha256 "70208a05e4716d4cb75b41b8287c77175e39d07af6db8df89281536308e14719"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-acp-v0.1.10-darwin-aarch64.tar.gz"
        sha256 "c57331d1a7e6bd9d69adadb99eab5d34c05a6cb2fc73cb09b23417439c021078"
      end
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-v0.1.10-linux-x86_64.tar.gz"
      sha256 "e807ef8ccf446fd0d1505181d4790be1159af9dd8cf6232b6014d492848f7369"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-cli-v0.1.10-linux-x86_64.tar.gz"
        sha256 "ba4e13fca3e72af9c49b841c200e443af25335597f6afce9a9b95f46811c0c57"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.10/lenso-agent-acp-v0.1.10-linux-x86_64.tar.gz"
        sha256 "b155fa6db143e7549855c003c22afe23977b51a5bac7453c59e82f78ed055e7b"
      end
    end
  end

  def install
    bin.install "lenso-agent"
    resources.each do |r|
      r.stage { bin.install r.name }
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lenso-agent --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-cli --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-acp --version")
    ENV["LENSO_AGENT_HOME"] = (testpath/"agent").to_s
    system bin/"lenso-agent-cli", "doctor", "--json"
  end
end
