# Generated by scripts/update-agent.py; update all artifacts together.
class LensoAgent < Formula
  desc "Coding agent with replaceable tools, models, and memory"
  homepage "https://github.com/LioRael/lenso-agent"
  license "MIT"

  depends_on "ripgrep"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :sequoia

    on_arm do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-v0.1.11-darwin-aarch64.tar.gz"
      sha256 "f666f1861b7cc36c053aefeffa2fc5f29c2195585b6c5e64457a3f5b51c755ea"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-cli-v0.1.11-darwin-aarch64.tar.gz"
        sha256 "e116ae2a5fbe59fb01b30fc511dd57acfa255298a8324da9552083a79145fc20"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-acp-v0.1.11-darwin-aarch64.tar.gz"
        sha256 "7c8d35a428f23876c82226cc1cf5fc9e87e0529073dcadb6b2591a67b6569939"
      end
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-v0.1.11-linux-x86_64.tar.gz"
      sha256 "ee303ba17b83c79283500e77823f0566951bf6cf035fe4ed00ab8c7919bfb329"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-cli-v0.1.11-linux-x86_64.tar.gz"
        sha256 "eca0c926989610b46f77ecf7842db36192c6866ba1a6f1a26dd844f561563420"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.11/lenso-agent-acp-v0.1.11-linux-x86_64.tar.gz"
        sha256 "75e151e3b96f0c188d9d056ef0bc0dbf71d5c36d17e88c9757ca93470491ef32"
      end
    end
  end

  def install
    bin.install "lenso-agent"
    resources.each do |r|
      r.stage { bin.install r.name }
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lenso-agent --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-cli --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-acp --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent acp --version")
    assert_match "lenso-agent run", shell_output("#{bin}/lenso-agent run --help")
    ENV["LENSO_AGENT_HOME"] = (testpath/"agent").to_s
    system bin/"lenso-agent", "doctor", "--json"
  end
end
