# Generated by scripts/update-agent.py; update all artifacts together.
class LensoAgent < Formula
  desc "Coding agent with replaceable tools, models, and memory"
  homepage "https://github.com/LioRael/lenso-agent"
  license "MIT"

  depends_on "ripgrep"

  on_macos do
    depends_on arch: :arm64
    depends_on macos: :sequoia

    on_arm do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-v0.1.13-darwin-aarch64.tar.gz"
      sha256 "b4eb42ae211ada82de459ab4c83b496af00e5f0b1a46c5e300aa1ab45af9e891"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-cli-v0.1.13-darwin-aarch64.tar.gz"
        sha256 "dfbea315e8a2cdedd1cfdc9c0304215af2583e2e0e62a541165db02ef2cb6049"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-acp-v0.1.13-darwin-aarch64.tar.gz"
        sha256 "349c12c1efe3e765ef605cc1ac6ff386e2ea67f4920c5fd8573ec1f890259fe0"
      end
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-v0.1.13-linux-x86_64.tar.gz"
      sha256 "68d432d3d9a740fe8ec8cc4be258ce28f2949e2419a9b5b561f49857f83179f0"

      resource "lenso-agent-cli" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-cli-v0.1.13-linux-x86_64.tar.gz"
        sha256 "da659db5af3b093b4e159b8c075d66257ccf681d0b10108071e518c7bcb5f906"
      end

      resource "lenso-agent-acp" do
        url "https://github.com/LioRael/lenso-agent/releases/download/v0.1.13/lenso-agent-acp-v0.1.13-linux-x86_64.tar.gz"
        sha256 "86b19e830d13e65bf29ba864bf5b18c9a989933849bb0ce09a8ab21d9cb5365c"
      end
    end
  end

  def install
    bin.install "lenso-agent"
    resources.each do |r|
      r.stage { bin.install r.name }
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lenso-agent --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-cli --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent-acp --version")
    assert_match version.to_s, shell_output("#{bin}/lenso-agent acp --version")
    assert_match "lenso-agent run", shell_output("#{bin}/lenso-agent run --help")
    ENV["LENSO_AGENT_HOME"] = (testpath/"agent").to_s
    system bin/"lenso-agent", "doctor", "--json"
  end
end
