#!/usr/bin/env python3
"""Pin the Formula to checksummed, published Agent release archives."""
import argparse
import re
from pathlib import Path
from urllib.request import urlopen


def render(version, checksums):
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version):
        raise ValueError("Use an exact Agent version, such as 0.1.10")
    root = f"https://github.com/LioRael/lenso-agent/releases/download/v{version}"
    lines = [
        "# Generated by scripts/update-agent.py; update all artifacts together.",
        "class LensoAgent < Formula",
        '  desc "Coding agent with replaceable tools, models, and memory"',
        '  homepage "https://github.com/LioRael/lenso-agent"',
        '  license "MIT"',
        "",
        '  depends_on "ripgrep"',
    ]
    for os_name, target, arch in [("macos", "darwin-aarch64", "arm64"), ("linux", "linux-x86_64", "x86_64")]:
        lines += ["", f"  on_{os_name} do", f"    depends_on arch: :{arch}"]
        if os_name == "macos":
            lines += ['    depends_on macos: :sequoia']
        lines += ["", "    on_arm do" if arch == "arm64" else "    on_intel do"]
        for binary in ["lenso-agent", "lenso-agent-cli", "lenso-agent-acp"]:
            archive = f"{binary}-v{version}-{target}.tar.gz"
            digest = checksums.get(archive, "")
            if not re.fullmatch(r"[a-f0-9]{64}", digest):
                raise ValueError(f"Missing or invalid release checksum: {archive}")
            indent = "      "
            if binary != "lenso-agent":
                lines += ["", f'      resource "{binary}" do']
                indent += "  "
            lines += [f'{indent}url "{root}/{archive}"', f'{indent}sha256 "{digest}"']
            if binary != "lenso-agent":
                lines += ["      end"]
        lines += ["    end", "  end"]
    lines += ["", "  def install", '    bin.install "lenso-agent"', "    resources.each do |r|", "      r.stage { bin.install r.name }", "    end", "  end", "", "  test do", '    assert_match version.to_s, shell_output("#{bin}/lenso-agent --version")', '    assert_match version.to_s, shell_output("#{bin}/lenso-agent-cli --version")', '    assert_match version.to_s, shell_output("#{bin}/lenso-agent-acp --version")', '    ENV["LENSO_AGENT_HOME"] = (testpath/"agent").to_s', '    system bin/"lenso-agent-cli", "doctor", "--json"', "  end", "end", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version")
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", args.version):
        parser.error("Use an exact Agent version, such as 0.1.10")
    url = f"https://github.com/LioRael/lenso-agent/releases/download/v{args.version}/SHA256SUMS"
    with urlopen(url, timeout=60) as response:
        content = response.read().decode()
    checksums = {}
    for line in content.splitlines():
        digest, filename = line.split()
        filename = filename.removeprefix("./")
        if filename in checksums:
            raise ValueError(f"Duplicate checksum entry: {filename}")
        checksums[filename] = digest
    formula = render(args.version, checksums)
    (Path(__file__).resolve().parent.parent / "Formula/lenso-agent.rb").write_text(formula)


if __name__ == "__main__":
    main()
